"""initial_schema

Revision ID: 1afe163031b7
Revises: 
Create Date: 2026-05-25 21:10:43.546419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afe163031b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stops_tournee_commande_id_fkey'), 'stops_tournee', type_='foreignkey')
    op.create_foreign_key(None, 'stops_tournee', 'commandes', ['commande_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stops_tournee', type_='foreignkey')
    op.create_foreign_key(op.f('stops_tournee_commande_id_fkey'), 'stops_tournee', 'commandes', ['commande_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
