"""initial schema

Revision ID: 3c0868df303c
Revises: 
Create Date: 2026-04-09 16:41:54.449467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0868df303c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taches_optimisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithme', sa.Enum('HEURISTIQUE', 'OR_TOOLS', name='algorithmeenum'), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EN_COURS', 'TERMINEE', 'ERREUR', name='statuttacheenum'), nullable=True),
    sa.Column('progression', sa.Integer(), nullable=True),
    sa.Column('temps_execution', sa.Float(), nullable=True),
    sa.Column('distance_totale', sa.Float(), nullable=True),
    sa.Column('nb_vehicules_utilises', sa.Integer(), nullable=True),
    sa.Column('nb_commandes_non_servies', sa.Integer(), nullable=True),
    sa.Column('date_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultat_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taches_optimisation_id'), 'taches_optimisation', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('EXPEDITEUR', 'DISPATCHEUR', 'CHAUFFEUR', 'ADMINISTRATEUR', name='roleenum'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(), nullable=False),
    sa.Column('capacite_poids', sa.Float(), nullable=False),
    sa.Column('capacite_volume', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('DISPONIBLE', 'EN_MISSION', 'HORS_SERVICE', name='statutvehiculeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_index(op.f('ix_vehicules_id'), 'vehicules', ['id'], unique=False)
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('adresse_enlevement', sa.String(), nullable=False),
    sa.Column('adresse_livraison', sa.String(), nullable=False),
    sa.Column('lat_enlevement', sa.Float(), nullable=False),
    sa.Column('lon_enlevement', sa.Float(), nullable=False),
    sa.Column('lat_livraison', sa.Float(), nullable=False),
    sa.Column('lon_livraison', sa.Float(), nullable=False),
    sa.Column('poids', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('date_livraison', sa.Date(), nullable=False),
    sa.Column('heure_ouverture', sa.Time(), nullable=False),
    sa.Column('heure_fermeture', sa.Time(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'AFFECTEE', 'EN_COURS', 'LIVREE', name='statutcommandeenum'), nullable=True),
    sa.Column('vehicule_id', sa.Integer(), nullable=True),
    sa.Column('chauffeur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commandes_id'), 'commandes', ['id'], unique=False)
    op.create_table('tournees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('distance_totale', sa.Float(), nullable=True),
    sa.Column('progression', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIEE', 'EN_COURS', 'TERMINEE', name='statuttourneeenum'), nullable=True),
    sa.Column('heure_depart', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('tache_optimisation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['tache_optimisation_id'], ['taches_optimisation.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournees_id'), 'tournees', ['id'], unique=False)
    op.create_table('stops_tournee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournee_id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('heure_arrivee_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_arrivee_reelle', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'EN_COURS', 'LIVREE', name='statutstopenum'), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['tournee_id'], ['tournees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_tournee_id'), 'stops_tournee', ['id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournee_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('RETARD', 'COLIS_ENDOMMAGE', 'ABSENCE_CLIENT', 'SIGNALEMENT_CHAUFFEUR', name='typeanomalieenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_signalement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('OUVERTE', 'RESOLUE', name='statutanomalieenum'), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stops_tournee.id'], ),
    sa.ForeignKeyConstraint(['tournee_id'], ['tournees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_stops_tournee_id'), table_name='stops_tournee')
    op.drop_table('stops_tournee')
    op.drop_index(op.f('ix_tournees_id'), table_name='tournees')
    op.drop_table('tournees')
    op.drop_index(op.f('ix_commandes_id'), table_name='commandes')
    op.drop_table('commandes')
    op.drop_index(op.f('ix_vehicules_id'), table_name='vehicules')
    op.drop_table('vehicules')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_taches_optimisation_id'), table_name='taches_optimisation')
    op.drop_table('taches_optimisation')
    # ### end Alembic commands ###
