"""add statut to utilisateur

Revision ID: 46cc9478f48e
Revises: 3c0868df303c
Create Date: 2026-04-25 20:45:14.960559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cc9478f48e'
down_revision: Union[str, Sequence[str], None] = '3c0868df303c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE statutchauffeurenum AS ENUM ('DISPONIBLE', 'EN_MISSION', 'HORS_SERVICE')")
    op.add_column('utilisateurs', sa.Column('statut', sa.Enum('DISPONIBLE', 'EN_MISSION', 'HORS_SERVICE', name='statutchauffeurenum'), nullable=True))

def downgrade() -> None:
    op.drop_column('utilisateurs', 'statut')
    op.execute("DROP TYPE statutchauffeurenum")
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'statut')
    # ### end Alembic commands ###
